# This is a basic workflow to help you get started with Actions

name: release them all BWUAHAHAHAH
on:
  workflow_dispatch:

# amberelec ark bookworm jammy noble pan4elec plucky rocknix uos   
# oslist: [ark amberelec, ark pan4elec, ark rocknix, ark uos, amberelec pan4elec, amberelec rocknix, amberelec uos, pan4elec rocknix, pan4elec uos, rocknix uos, ark amberelec pan4elec, ark amberelec rocknix, ark amberelec uos, ark pan4elec rocknix, ark pan4elec uos, ark rocknix uos, amberelec pan4elec rocknix, amberelec pan4elec uos, amberelec rocknix uos, pan4elec rocknix uos, ark amberelec pan4elec rocknix, ark amberelec pan4elec uos, ark amberelec rocknix uos, ark pan4elec rocknix uos, amberelec pan4elec rocknix uos, ark amberelec pan4elec rocknix uos]
# armbian: [NoArmbian, bookworm, jammy, noble, plucky]

jobs:
  get_build_date:
    runs-on: ubuntu-latest
    outputs:
      build_datedash: ${{ steps.set_date.outputs.datedash }}
      build_date: ${{ steps.set_date.outputs.date }}
    steps:
      - name: Set build date
        id: set_date
        run:  |
          echo "datedash=$(date +%Y-%m-%d-%H%M%S)" >> $GITHUB_OUTPUT 
          echo "date=$(echo $datedash | sed 's|\-||g')" >> $GITHUB_OUTPUT 

  
  build:
    strategy:
      matrix:
        # amberelec ark bookworm jammy noble pan4elec plucky rocknix uos   
        oslist: [ark amberelec, ark pan4elec, ark rocknix, ark uos, amberelec pan4elec, amberelec rocknix, amberelec uos, pan4elec rocknix, pan4elec uos, rocknix uos, ark amberelec pan4elec, ark amberelec rocknix, ark amberelec uos, ark pan4elec rocknix, ark pan4elec uos, ark rocknix uos, amberelec pan4elec rocknix, amberelec pan4elec uos, amberelec rocknix uos, pan4elec rocknix uos, ark amberelec pan4elec rocknix, ark amberelec pan4elec uos, ark amberelec rocknix uos, ark pan4elec rocknix uos, amberelec pan4elec rocknix uos, ark amberelec pan4elec rocknix uos]
        armbian: [NoArmbian, bookworm, jammy, noble, plucky]
        include:
          - oslist: amberelec ark pan4elec rocknix uos
            armbian: bookworm jammy noble plucky
          - armbian: bookworm jammy noble plucky
      fail-fast: false
    runs-on: ubuntu-latest
    needs: get_build_date

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
          
      - uses: actions/checkout@v4

      - name: Build img
        run: |
          export BuildImgEnv=github 
          export UBootBuilderRepo=$(echo $GITHUB_REPOSITORY | cut -d/ -f1)
          echo UBootBuilderRepo=${UBootBuilderRepo}
          [[ "${{ matrix.armbian }}" = NoArmbian ]] && export RealOSList="${{ matrix.oslist }}" || export RealOSList="${{ matrix.oslist }} ${{ matrix.armbian }}"
          echo RealOSList=$RealOSList  
          chmod a+x ./buildimg.sh 
          ./buildimg.sh $RealOSList 
          echo df -h /
          df -h /
          echo df end

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: R36S-Multiboot-*.img.xz.7z.*
          draft: true
          name: build ${{ needs.get_build_date.outputs.build_datedash }}
          tag_name: v${{ needs.get_build_date.outputs.build_date }}
