# This is a basic workflow to help you get started with Actions

name: release ArkBiaNix
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
          
      - uses: actions/checkout@v4


      - name: Build img
        run: |
          export BuildImgEnv=github 
          chmod a+x ./buildimg.sh ark rocknix armbian
          ./buildimg.sh ark rocknix armbian
          echo df -h /
          df -h /
          echo df end



      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: |
      #       u-boot-r36s.bin
      #       u-boot-r36s.tar
      #     draft: true
