# This is a basic workflow to help you get started with Actions

name: release ArkBiaNix
on:
  workflow_dispatch:

# amberelec ark bookworm jammy noble pan4elec plucky rocknix uos   
# oslist: [ark amberelec, ark pan4elec, ark rocknix, ark uos, amberelec pan4elec, amberelec rocknix, amberelec uos, pan4elec rocknix, pan4elec uos, rocknix uos, ark amberelec pan4elec, ark amberelec rocknix, ark amberelec uos, ark pan4elec rocknix, ark pan4elec uos, ark rocknix uos, amberelec pan4elec rocknix, amberelec pan4elec uos, amberelec rocknix uos, pan4elec rocknix uos, ark amberelec pan4elec rocknix, ark amberelec pan4elec uos, ark amberelec rocknix uos, ark pan4elec rocknix uos, amberelec pan4elec rocknix uos, ark amberelec pan4elec rocknix uos]
# armbian: [NoArmbian, bookworm, jammy, noble, plucky]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
          
      - uses: actions/checkout@v4


      - name: Build img
        run: |
          export BuildImgEnv=github 
          export UBootBuilderRepo=$(echo $GITHUB_REPOSITORY | cut -d/ -f1)
          echo UBootBuilderRepo=${UBootBuilderRepo}
          chmod a+x ./buildimg.sh ark rocknix armbian
          ./buildimg.sh ark rocknix armbian
          echo df -h /
          df -h /
          echo df end

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: R36S-Multiboot-ark-rocknix-armbian-*.img.xz.7z.*
          draft: true
