# This is a basic workflow to help you get started with Actions

name: release them all BWUAHAHAHAH
on:
  workflow_dispatch:

jobs:
  get_build_date:
    runs-on: ubuntu-latest
    outputs:
      build_datedash: ${{ steps.set_date.outputs.datedash }}
      build_date: ${{ steps.set_date.outputs.date }}
    steps:
      - name: Set build date
        id: set_date
        run:  |
          export datenow=$(date +%Y-%m-%d-%H%M%S)
          echo "datedash=$(echo $datenow)" >> $GITHUB_OUTPUT 
          echo "date=$(echo $datenow | sed 's|\-||g')" >> $GITHUB_OUTPUT 


  build:
    strategy:
      matrix:
        # amberelec ark pan4elec rocknix uos   
        # bookworm jammy noble plucky
        # oslist: [ark amberelec, ark pan4elec, ark rocknix, ark uos, amberelec pan4elec, amberelec rocknix, amberelec uos, pan4elec rocknix, pan4elec uos, rocknix uos, ark amberelec pan4elec, ark amberelec rocknix, ark amberelec uos, ark pan4elec rocknix, ark pan4elec uos, ark rocknix uos, amberelec pan4elec rocknix, amberelec pan4elec uos, amberelec rocknix uos, pan4elec rocknix uos, ark amberelec pan4elec rocknix, ark amberelec pan4elec uos, ark amberelec rocknix uos, ark pan4elec rocknix uos, amberelec pan4elec rocknix uos, ark amberelec pan4elec rocknix uos]
        amberelec:  [amberelec, skipamberelec]
        ark:        [ark, skipark]
        pan4elec:   [pan4elec, skippan4elec]
        rocknix:    [rocknix, skiprocknix]
        uos:        [uos, skipuos]
        armbian:    [skiparmbian, bookworm, jammy, noble, plucky]
        include:
          - armbian: bookworm jammy noble plucky
        exclude:
          - amberelec: skipamberelec
            ark: skipark
            pan4elec: skippan4elec
            rocknix: skiprocknix
            uos: skipuos
            armbian: skiparmbian
          - amberelec: skipamberelec
            ark: skipark
            pan4elec: skippan4elec
            rocknix: skiprocknix
            uos: skipuos
            armbian: bookworm
          - amberelec: skipamberelec
            ark: skipark
            pan4elec: skippan4elec
            rocknix: skiprocknix
            uos: skipuos
            armbian: jammy
          - amberelec: skipamberelec
            ark: skipark
            pan4elec: skippan4elec
            rocknix: skiprocknix
            uos: skipuos
            armbian: noble
          - amberelec: skipamberelec
            ark: skipark
            pan4elec: skippan4elec
            rocknix: skiprocknix
            uos: skipuos
            armbian: plucky

            
      fail-fast: true
    runs-on: ubuntu-latest
    needs: get_build_date

    steps:
      - name: Skip unwanted jobs
        if: |
          matrix.amberelec == 'skipamberelec' &&
          matrix.ark == 'skipark' &&
          matrix.pan4elec == 'skippan4elec' &&
          matrix.rocknix == 'skiprocknix' &&
          matrix.uos == 'skipuos' &&
          (
            matrix.armbian == 'skiparmbian' ||
            matrix.armbian == 'bookworm' ||
            matrix.armbian == 'jammy' ||
            matrix.armbian == 'noble' ||
            matrix.armbian == 'plucky'
          )
        run: |
          echo "This is an excluded combination, skipping."
          exit 0

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          #dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
          
      - uses: actions/checkout@v4

      

      - name: Build img
        run: |
          export BuildImgEnv=github 
          export UBootBuilderRepo=$(echo $GITHUB_REPOSITORY | cut -d/ -f1)
          export GH_build_date=${{ needs.get_build_date.outputs.build_date }}
          echo UBootBuilderRepo=${UBootBuilderRepo}
          for i in ${{ matrix.amberelec }} ${{ matrix.ark }} ${{ matrix.pan4elec }} ${{ matrix.rocknix }} ${{ matrix.uos }}
          do 
            [[ $i == "skip"* ]] && continue
            export NewOSList=$NewOSList $i
          done
          [[ ! "${{ matrix.armbian }}" = skiparmbian ]] && export NewOSList="$NewOSList ${{ matrix.armbian }}"
          export NewOSList="$(echo $NewOSList| xargs)"
          echo NewOSList=$NewOSList  
          chmod a+x ./buildimg.sh 
          ./buildimg.sh $NewOSList
          echo df -h /
          df -h /
          echo df end

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: R36S-Multiboot-*.img.xz.7z.*
          draft: true
          name: batch ${{ needs.get_build_date.outputs.build_datedash }}
          tag_name: v${{ needs.get_build_date.outputs.build_date }}
